type SearchingItemType = {
  id: string;
  symbol: string;
  label: string;
};

export const currencyList: Array<SearchingItemType> = [
  { id: 'currency_AFA', symbol: 'AFA', label: 'Afghan Afghani' },
  { id: 'currency_ALL', symbol: 'ALL', label: 'Albanian Lek' },
  { id: 'currency_DZD', symbol: 'DZD', label: 'Algerian Dinar' },
  { id: 'currency_AOA', symbol: 'AOA', label: 'Angolan Kwanza' },
  { id: 'currency_ARS', symbol: 'ARS', label: 'Argentine Peso' },
  { id: 'currency_AMD', symbol: 'AMD', label: 'Armenian Dram' },
  { id: 'currency_AWG', symbol: 'AWG', label: 'Aruban Florin' },
  { id: 'currency_AUD', symbol: 'AUD', label: 'Australian Dollar' },
  { id: 'currency_AZN', symbol: 'AZN', label: 'Azerbaijani Manat' },
  { id: 'currency_BSD', symbol: 'BSD', label: 'Bahamian Dollar' },
  { id: 'currency_BHD', symbol: 'BHD', label: 'Bahraini Dinar' },
  { id: 'currency_BDT', symbol: 'BDT', label: 'Bangladeshi Taka' },
  { id: 'currency_BBD', symbol: 'BBD', label: 'Barbadian Dollar' },
  { id: 'currency_BYR', symbol: 'BYR', label: 'Belarusian Ruble' },
  { id: 'currency_BEF', symbol: 'BEF', label: 'Belgian Franc' },
  { id: 'currency_BZD', symbol: 'BZD', label: 'Belize Dollar' },
  { id: 'currency_BMD', symbol: 'BMD', label: 'Bermudan Dollar' },
  { id: 'currency_BTN', symbol: 'BTN', label: 'Bhutanese Ngultrum' },
  { id: 'currency_BTC', symbol: 'BTC', label: 'Bitcoin' },
  { id: 'currency_BOB', symbol: 'BOB', label: 'Bolivian Boliviano' },
  {
    id: 'currency_BAM',
    symbol: 'BAM',
    label: 'Bosnia-Herzegovina Convertible Mark',
  },
  { id: 'currency_BWP', symbol: 'BWP', label: 'Botswanan Pula' },
  { id: 'currency_BRL', symbol: 'BRL', label: 'Brazilian Real' },
  { id: 'currency_GBP', symbol: 'GBP', label: 'British Pound Sterling' },
  { id: 'currency_BND', symbol: 'BND', label: 'Brunei Dollar' },
  { id: 'currency_BGN', symbol: 'BGN', label: 'Bulgarian Lev' },
  { id: 'currency_BIF', symbol: 'BIF', label: 'Burundian Franc' },
  { id: 'currency_KHR', symbol: 'KHR', label: 'Cambodian Riel' },
  { id: 'currency_CAD', symbol: 'CAD', label: 'Canadian Dollar' },
  { id: 'currency_CVE', symbol: 'CVE', label: 'Cape Verdean Escudo' },
  { id: 'currency_KYD', symbol: 'KYD', label: 'Cayman Islands Dollar' },
  { id: 'currency_XOF', symbol: 'XOF', label: 'CFA Franc BCEAO' },
  { id: 'currency_XAF', symbol: 'XAF', label: 'CFA Franc BEAC' },
  { id: 'currency_XPF', symbol: 'XPF', label: 'CFP Franc' },
  { id: 'currency_CLP', symbol: 'CLP', label: 'Chilean Peso' },
  { id: 'currency_CNY', symbol: 'CNY', label: 'Chinese Yuan' },
  { id: 'currency_COP', symbol: 'COP', label: 'Colombian Peso' },
  { id: 'currency_KMF', symbol: 'KMF', label: 'Comorian Franc' },
  { id: 'currency_CDF', symbol: 'CDF', label: 'Congolese Franc' },
  { id: 'currency_CRC', symbol: 'CRC', label: 'Costa Rican ColÃ³n' },
  { id: 'currency_HRK', symbol: 'HRK', label: 'Croatian Kuna' },
  { id: 'currency_CUC', symbol: 'CUC', label: 'Cuban Convertible Peso' },
  { id: 'currency_CZK', symbol: 'CZK', label: 'Czech Republic Koruna' },
  { id: 'currency_DKK', symbol: 'DKK', label: 'Danish Krone' },
  { id: 'currency_DJF', symbol: 'DJF', label: 'Djiboutian Franc' },
  { id: 'currency_DOP', symbol: 'DOP', label: 'Dominican Peso' },
  { id: 'currency_XCD', symbol: 'XCD', label: 'East Caribbean Dollar' },
  { id: 'currency_EGP', symbol: 'EGP', label: 'Egyptian Pound' },
  { id: 'currency_ERN', symbol: 'ERN', label: 'Eritrean Nakfa' },
  { id: 'currency_EEK', symbol: 'EEK', label: 'Estonian Kroon' },
  { id: 'currency_ETB', symbol: 'ETB', label: 'Ethiopian Birr' },
  { id: 'currency_EUR', symbol: 'EUR', label: 'Euro' },
  { id: 'currency_FKP', symbol: 'FKP', label: 'Falkland Islands Pound' },
  { id: 'currency_FJD', symbol: 'FJD', label: 'Fijian Dollar' },
  { id: 'currency_GMD', symbol: 'GMD', label: 'Gambian Dalasi' },
  { id: 'currency_GEL', symbol: 'GEL', label: 'Georgian Lari' },
  { id: 'currency_DEM', symbol: 'DEM', label: 'German Mark' },
  { id: 'currency_GHS', symbol: 'GHS', label: 'Ghanaian Cedi' },
  { id: 'currency_GIP', symbol: 'GIP', label: 'Gibraltar Pound' },
  { id: 'currency_GRD', symbol: 'GRD', label: 'Greek Drachma' },
  { id: 'currency_GTQ', symbol: 'GTQ', label: 'Guatemalan Quetzal' },
  { id: 'currency_GNF', symbol: 'GNF', label: 'Guinean Franc' },
  { id: 'currency_GYD', symbol: 'GYD', label: 'Guyanaese Dollar' },
  { id: 'currency_HTG', symbol: 'HTG', label: 'Haitian Gourde' },
  { id: 'currency_HNL', symbol: 'HNL', label: 'Honduran Lempira' },
  { id: 'currency_HKD', symbol: 'HKD', label: 'Hong Kong Dollar' },
  { id: 'currency_HUF', symbol: 'HUF', label: 'Hungarian Forint' },
  { id: 'currency_ISK', symbol: 'ISK', label: 'Icelandic KrÃ³na' },
  { id: 'currency_INR', symbol: 'INR', label: 'Indian Rupee' },
  { id: 'currency_IDR', symbol: 'IDR', label: 'Indonesian Rupiah' },
  { id: 'currency_IRR', symbol: 'IRR', label: 'Iranian Rial' },
  { id: 'currency_IQD', symbol: 'IQD', label: 'Iraqi Dinar' },
  { id: 'currency_ILS', symbol: 'ILS', label: 'Israeli New Sheqel' },
  { id: 'currency_ITL', symbol: 'ITL', label: 'Italian Lira' },
  { id: 'currency_JMD', symbol: 'JMD', label: 'Jamaican Dollar' },
  { id: 'currency_JPY', symbol: 'JPY', label: 'Japanese Yen' },
  { id: 'currency_JOD', symbol: 'JOD', label: 'Jordanian Dinar' },
  { id: 'currency_KZT', symbol: 'KZT', label: 'Kazakhstani Tenge' },
  { id: 'currency_KES', symbol: 'KES', label: 'Kenyan Shilling' },
  { id: 'currency_KWD', symbol: 'KWD', label: 'Kuwaiti Dinar' },
  { id: 'currency_KGS', symbol: 'KGS', label: 'Kyrgystani Som' },
  { id: 'currency_LAK', symbol: 'LAK', label: 'Laotian Kip' },
  { id: 'currency_LVL', symbol: 'LVL', label: 'Latvian Lats' },
  { id: 'currency_LBP', symbol: 'LBP', label: 'Lebanese Pound' },
  { id: 'currency_LSL', symbol: 'LSL', label: 'Lesotho Loti' },
  { id: 'currency_LRD', symbol: 'LRD', label: 'Liberian Dollar' },
  { id: 'currency_LYD', symbol: 'LYD', label: 'Libyan Dinar' },
  { id: 'currency_LTL', symbol: 'LTL', label: 'Lithuanian Litas' },
  { id: 'currency_MOP', symbol: 'MOP', label: 'Macanese Pataca' },
  { id: 'currency_MKD', symbol: 'MKD', label: 'Macedonian Denar' },
  { id: 'currency_MGA', symbol: 'MGA', label: 'Malagasy Ariary' },
  { id: 'currency_MWK', symbol: 'MWK', label: 'Malawian Kwacha' },
  { id: 'currency_MYR', symbol: 'MYR', label: 'Malaysian Ringgit' },
  { id: 'currency_MVR', symbol: 'MVR', label: 'Maldivian Rufiyaa' },
  { id: 'currency_MRO', symbol: 'MRO', label: 'Mauritanian Ouguiya' },
  { id: 'currency_MUR', symbol: 'MUR', label: 'Mauritian Rupee' },
  { id: 'currency_MXN', symbol: 'MXN', label: 'Mexican Peso' },
  { id: 'currency_MDL', symbol: 'MDL', label: 'Moldovan Leu' },
  { id: 'currency_MNT', symbol: 'MNT', label: 'Mongolian Tugrik' },
  { id: 'currency_MAD', symbol: 'MAD', label: 'Moroccan Dirham' },
  { id: 'currency_MZM', symbol: 'MZM', label: 'Mozambican Metical' },
  { id: 'currency_MMK', symbol: 'MMK', label: 'Myanmar Kyat' },
  { id: 'currency_NAD', symbol: 'NAD', label: 'Namibian Dollar' },
  { id: 'currency_NPR', symbol: 'NPR', label: 'Nepalese Rupee' },
  { id: 'currency_ANG', symbol: 'ANG', label: 'Netherlands Antillean Guilder' },
  { id: 'currency_TWD', symbol: 'TWD', label: 'New Taiwan Dollar' },
  { id: 'currency_NZD', symbol: 'NZD', label: 'New Zealand Dollar' },
  { id: 'currency_NIO', symbol: 'NIO', label: 'Nicaraguan CÃ³rdoba' },
  { id: 'currency_NGN', symbol: 'NGN', label: 'Nigerian Naira' },
  { id: 'currency_KPW', symbol: 'KPW', label: 'North Korean Won' },
  { id: 'currency_NOK', symbol: 'NOK', label: 'Norwegian Krone' },
  { id: 'currency_OMR', symbol: 'OMR', label: 'Omani Rial' },
  { id: 'currency_PKR', symbol: 'PKR', label: 'Pakistani Rupee' },
  { id: 'currency_PAB', symbol: 'PAB', label: 'Panamanian Balboa' },
  { id: 'currency_PGK', symbol: 'PGK', label: 'Papua New Guinean Kina' },
  { id: 'currency_PYG', symbol: 'PYG', label: 'Paraguayan Guarani' },
  { id: 'currency_PEN', symbol: 'PEN', label: 'Peruvian Nuevo Sol' },
  { id: 'currency_PHP', symbol: 'PHP', label: 'Philippine Peso' },
  { id: 'currency_PLN', symbol: 'PLN', label: 'Polish Zloty' },
  { id: 'currency_QAR', symbol: 'QAR', label: 'Qatari Rial' },
  { id: 'currency_RON', symbol: 'RON', label: 'Romanian Leu' },
  { id: 'currency_RUB', symbol: 'RUB', label: 'Russian Ruble' },
  { id: 'currency_RWF', symbol: 'RWF', label: 'Rwandan Franc' },
  { id: 'currency_SVC', symbol: 'SVC', label: 'Salvadoran ColÃ³n' },
  { id: 'currency_WST', symbol: 'WST', label: 'Samoan Tala' },
  { id: 'currency_SAR', symbol: 'SAR', label: 'Saudi Riyal' },
  { id: 'currency_RSD', symbol: 'RSD', label: 'Serbian Dinar' },
  { id: 'currency_SCR', symbol: 'SCR', label: 'Seychellois Rupee' },
  { id: 'currency_SLL', symbol: 'SLL', label: 'Sierra Leonean Leone' },
  { id: 'currency_SGD', symbol: 'SGD', label: 'Singapore Dollar' },
  { id: 'currency_SKK', symbol: 'SKK', label: 'Slovak Koruna' },
  { id: 'currency_SBD', symbol: 'SBD', label: 'Solomon Islands Dollar' },
  { id: 'currency_SOS', symbol: 'SOS', label: 'Somali Shilling' },
  { id: 'currency_ZAR', symbol: 'ZAR', label: 'South African Rand' },
  { id: 'currency_KRW', symbol: 'KRW', label: 'South Korean Won' },
  { id: 'currency_XDR', symbol: 'XDR', label: 'Special Drawing Rights' },
  { id: 'currency_LKR', symbol: 'LKR', label: 'Sri Lankan Rupee' },
  { id: 'currency_SHP', symbol: 'SHP', label: 'St. Helena Pound' },
  { id: 'currency_SDG', symbol: 'SDG', label: 'Sudanese Pound' },
  { id: 'currency_SRD', symbol: 'SRD', label: 'Surinamese Dollar' },
  { id: 'currency_SZL', symbol: 'SZL', label: 'Swazi Lilangeni' },
  { id: 'currency_SEK', symbol: 'SEK', label: 'Swedish Krona' },
  { id: 'currency_CHF', symbol: 'CHF', label: 'Swiss Franc' },
  { id: 'currency_SYP', symbol: 'SYP', label: 'Syrian Pound' },
  { id: 'currency_STD', symbol: 'STD', label: 'São Tomé and Príncipe Dobra' },
  { id: 'currency_TJS', symbol: 'TJS', label: 'Tajikistani Somoni' },
  { id: 'currency_TZS', symbol: 'TZS', label: 'Tanzanian Shilling' },
  { id: 'currency_THB', symbol: 'THB', label: 'Thai Baht' },
  { id: 'currency_TOP', symbol: 'TOP', label: "Tongan Pa'anga" },
  { id: 'currency_TTD', symbol: 'TTD', label: 'Trinidad & Tobago Dollar' },
  { id: 'currency_TND', symbol: 'TND', label: 'Tunisian Dinar' },
  { id: 'currency_TRY', symbol: 'TRY', label: 'Turkish Lira' },
  { id: 'currency_TMT', symbol: 'TMT', label: 'Turkmenistani Manat' },
  { id: 'currency_UGX', symbol: 'UGX', label: 'Ugandan Shilling' },
  { id: 'currency_UAH', symbol: 'UAH', label: 'Ukrainian Hryvnia' },
  { id: 'currency_AED', symbol: 'AED', label: 'United Arab Emirates Dirham' },
  { id: 'currency_UYU', symbol: 'UYU', label: 'Uruguayan Peso' },
  { id: 'currency_USD', symbol: 'USD', label: 'US Dollar' },
  { id: 'currency_UZS', symbol: 'UZS', label: 'Uzbekistan Som' },
  { id: 'currency_VUV', symbol: 'VUV', label: 'Vanuatu Vatu' },
  { id: 'currency_VEF', symbol: 'VEF', label: 'Venezuelan BolÃvar' },
  { id: 'currency_VND', symbol: 'VND', label: 'Vietnamese Dong' },
  { id: 'currency_YER', symbol: 'YER', label: 'Yemeni Rial' },
  { id: 'currency_ZMK', symbol: 'ZMK', label: 'Zambian Kwacha' },
];

export const cryptoCurrencies: Array<{
  id: string;
  name: string;
  symbol: string;
}> = [
  {
    id: 'BTC',
    name: 'Bitcoin',
    symbol: 'BTC',
  },
  {
    id: 'ETH',
    name: 'Ethereum',
    symbol: 'ETH',
  },
  {
    id: 'XRP',
    name: 'Ripple',
    symbol: 'XRP',
  },
  {
    id: 'BCH',
    name: 'Bitcoin Cash',
    symbol: 'BCH',
  },
  {
    id: 'LTC',
    name: 'Litecoin',
    symbol: 'LTC',
  },
  {
    id: 'USDT',
    name: 'Tether',
    symbol: 'USDT',
  },
  {
    id: 'DASH',
    name: 'Dash',
    symbol: 'DASH',
  },
  {
    id: 'XEM',
    name: 'NEM',
    symbol: 'XEM',
  },
  {
    id: 'BCC',
    name: 'BitConnect',
    symbol: 'BCC',
  },
  {
    id: 'NEO',
    name: 'NEO',
    symbol: 'NEO',
  },
  {
    id: 'XMR',
    name: 'Monero',
    symbol: 'XMR',
  },
  {
    id: 'MIOTA',
    name: 'IOTA',
    symbol: 'MIOTA',
  },
  {
    id: 'ETC',
    name: 'Ethereum Classic',
    symbol: 'ETC',
  },
  {
    id: 'OMG',
    name: 'OmiseGO',
    symbol: 'OMG',
  },
  {
    id: 'ADA',
    name: 'Cardano',
    symbol: 'ADA',
  },
  {
    id: 'QTUM',
    name: 'Qtum',
    symbol: 'QTUM',
  },
  {
    id: 'LSK',
    name: 'Lisk',
    symbol: 'LSK',
  },
  {
    id: 'ZEC',
    name: 'Zcash',
    symbol: 'ZEC',
  },
  {
    id: 'WAVES',
    name: 'Waves',
    symbol: 'WAVES',
  },
  {
    id: 'HSR',
    name: 'Hshare',
    symbol: 'HSR',
  },
  {
    id: 'STRAT',
    name: 'Stratis',
    symbol: 'STRAT',
  },
  {
    id: 'XLM',
    name: 'Stellar Lumens',
    symbol: 'XLM',
  },
  {
    id: 'BCN',
    name: 'Bytecoin',
    symbol: 'BCN',
  },
];
export const cryptoCurrencies2: Array<SearchingItemType> = [
  { id: 'coin_MNE', symbol: 'MNE', label: 'Minereum' },
  { id: 'coin_UNIFY', symbol: 'UNIFY', label: 'Unify' },
  { id: 'coin_LGD', symbol: 'LGD', label: 'Legends Room' },
  { id: 'coin_ICOO', symbol: 'ICOO', label: 'ICO OpenLedger' },
  { id: 'coin_HUC', symbol: 'HUC', label: 'HunterCoin' },
  { id: 'coin_XP', symbol: 'XP', label: 'XP' },
  { id: 'coin_SKIN', symbol: 'SKIN', label: 'SkinCoin' },
  { id: 'coin_ONX', symbol: 'ONX', label: 'Onix' },
  { id: 'coin_1337', symbol: '1337', label: '1337' },
  { id: 'coin_ADZ', symbol: 'ADZ', label: 'Adzcoin' },
  { id: 'coin_INXT', symbol: 'INXT', label: 'Internxt' },
  { id: 'coin_KOBO', symbol: 'KOBO', label: 'Kobocoin' },
  { id: 'coin_FST', symbol: 'FST', label: 'Fastcoin' },
  { id: 'coin_MAO', symbol: 'MAO', label: 'Mao Zedong' },
  { id: 'coin_MRT', symbol: 'MRT', label: 'Miners&#39; Rewar...' },
  { id: 'coin_EBTC', symbol: 'EBTC', label: 'eBTC' },
  { id: 'coin_INFX', symbol: 'INFX', label: 'Influxcoin' },
  { id: 'coin_XMCC', symbol: 'XMCC', label: 'MonacoCoin' },
  { id: 'coin_DAR', symbol: 'DAR', label: 'Darcrus' },
  { id: 'coin_IFC', symbol: 'IFC', label: 'Infinitecoin' },
  { id: 'coin_XHI', symbol: 'XHI', label: 'HiCoin' },
  { id: 'coin_CRM', symbol: 'CRM', label: 'Cream' },
  { id: 'coin_DOT', symbol: 'DOT', label: 'Dotcoin' },
  { id: 'coin_WDC', symbol: 'WDC', label: 'WorldCoin' },
  { id: 'coin_NETKO', symbol: 'NETKO', label: 'Netko' },
  { id: 'coin_GRWI', symbol: 'GRWI', label: 'Growers Inter...' },
  { id: 'coin_RUP', symbol: 'RUP', label: 'Rupee' },
  { id: 'coin_ZCC', symbol: 'ZCC', label: 'ZcCoin' },
  { id: 'coin_CPC', symbol: 'CPC', label: 'Capricoin' },
  { id: 'coin_BYC', symbol: 'BYC', label: 'Bytecent' },
  { id: 'coin_ARC', symbol: 'ARC', label: 'ArcticCoin' },
  { id: 'coin_BRIT', symbol: 'BRIT', label: 'BritCoin' },
  { id: 'coin_SUMO', symbol: 'SUMO', label: 'Sumokoin' },
  { id: 'coin_EBET', symbol: 'EBET', label: 'EthBet' },
  { id: 'coin_USNBT', symbol: 'USNBT', label: 'NuBits' },
  { id: 'coin_TES', symbol: 'TES', label: 'TeslaCoin' },
  { id: 'coin_ETHD', symbol: 'ETHD', label: 'Ethereum Dark' },
  { id: 'coin_INSN', symbol: 'INSN', label: 'InsaneCoin' },
  { id: 'coin_STRC', symbol: 'STRC', label: 'StarCredits' },
  { id: 'coin_DCY', symbol: 'DCY', label: 'Dinastycoin' },
  { id: 'coin_MEC', symbol: 'MEC', label: 'Megacoin' },
  { id: 'coin_ZOI', symbol: 'ZOI', label: 'Zoin' },
  { id: 'coin_HNC', symbol: 'HNC', label: 'Helleniccoin' },
  { id: 'coin_LDOGE', symbol: 'LDOGE', label: 'LiteDoge' },
  { id: 'coin_FUCK', symbol: 'FUCK', label: 'FuckToken' },
  { id: 'coin_FJC', symbol: 'FJC', label: 'FujiCoin' },
  { id: 'coin_KEK', symbol: 'KEK', label: 'KekCoin' },
  { id: 'coin_FAL', symbol: 'FAL', label: 'Falcoin' },
  { id: 'coin_VSX', symbol: 'VSX', label: 'Vsync' },
  { id: 'coin_XFT', symbol: 'XFT', label: 'Footy Cash' },
  { id: 'coin_TKR', symbol: 'TKR', label: 'Trackr' },
  { id: 'coin_BTA', symbol: 'BTA', label: 'Bata' },
  { id: 'coin_BRO', symbol: 'BRO', label: 'Bitradio' },
  { id: 'coin_POS', symbol: 'POS', label: 'PoSToken' },
  { id: 'coin_TIPS', symbol: 'TIPS', label: 'FedoraCoin' },
  { id: 'coin_TZC', symbol: 'TZC', label: 'TrezarCoin' },
  { id: 'coin_BLAS', symbol: 'BLAS', label: 'BlakeStar' },
  { id: 'coin_XBL', symbol: 'XBL', label: 'Billionaire T...' },
  { id: 'coin_FCN', symbol: 'FCN', label: 'Fantomcoin' },
  { id: 'coin_TYCHO', symbol: 'TYCHO', label: 'Tychocoin' },
  { id: 'coin_MOIN', symbol: 'MOIN', label: 'Moin' },
  { id: 'coin_KRB', symbol: 'KRB', label: 'Karbowanec' },
  { id: 'coin_DP', symbol: 'DP', label: 'DigitalPrice' },
  { id: 'coin_DDF', symbol: 'DDF', label: 'DigitalDevelo...' },
  { id: 'coin_HTC', symbol: 'HTC', label: 'HitCoin' },
  { id: 'coin_TRI', symbol: 'TRI', label: 'Triangles' },
  { id: 'coin_NTO', symbol: 'NTO', label: 'Fujinto' },
  { id: 'coin_UNB', symbol: 'UNB', label: 'UnbreakableCoin' },
  { id: 'coin_RLT', symbol: 'RLT', label: 'RouletteToken' },
  { id: 'coin_NYC', symbol: 'NYC', label: 'NewYorkCoin' },
  { id: 'coin_CWXT', symbol: 'CWXT', label: 'CryptoWorldX ...' },
  { id: 'coin_NOBL', symbol: 'NOBL', label: 'NobleCoin' },
  { id: 'coin_DNR', symbol: 'DNR', label: 'Denarius' },
  { id: 'coin_RUSTBITS', symbol: 'RUSTBITS', label: 'Rustbits' },
  { id: 'coin_LINX', symbol: 'LINX', label: 'Linx' },
  { id: 'coin_NET', symbol: 'NET', label: 'NetCoin' },
  { id: 'coin_42', symbol: '42', label: '42-coin' },
  { id: 'coin_JET', symbol: 'JET', label: 'Jetcoin' },
  { id: 'coin_POST', symbol: 'POST', label: 'PostCoin' },
  { id: 'coin_WGO', symbol: 'WGO', label: 'WavesGo' },
  { id: 'coin_UIS', symbol: 'UIS', label: 'Unitus' },
  { id: 'coin_ECA', symbol: 'ECA', label: 'Electra' },
  { id: 'coin_XVP', symbol: 'XVP', label: 'Virtacoinplus' },
  { id: 'coin_ZER', symbol: 'ZER', label: 'Zero' },
  { id: 'coin_FXE', symbol: 'FXE', label: 'FuturXe' },
  { id: 'coin_NEWB', symbol: 'NEWB', label: 'Newbium' },
  { id: 'coin_PIE', symbol: 'PIE', label: 'PIECoin' },
  { id: 'coin_EMP', symbol: 'EMP', label: 'EMoneyPower' },
  { id: 'coin_DAXX', symbol: 'DAXX', label: 'DaxxCoin' },
  { id: 'coin_SCORE', symbol: 'SCORE', label: 'Scorecoin' },
  { id: 'coin_DAS', symbol: 'DAS', label: 'DAS' },
  { id: 'coin_BUCKS', symbol: 'BUCKS', label: 'SwagBucks' },
  { id: 'coin_MAC', symbol: 'MAC', label: 'Machinecoin' },
  { id: 'coin_PROC', symbol: 'PROC', label: 'ProCurrency' },
  { id: 'coin_VLT', symbol: 'VLT', label: 'Veltor' },
  { id: 'coin_TRUMP', symbol: 'TRUMP', label: 'TrumpCoin' },
  { id: 'coin_DALC', symbol: 'DALC', label: 'Dalecoin' },
  { id: 'coin_DEM', symbol: 'DEM', label: 'Deutsche eMark' },
  { id: 'coin_ENT', symbol: 'ENT', label: 'Eternity' },
  { id: 'coin_RBIES', symbol: 'RBIES', label: 'Rubies' },
  { id: 'coin_WOMEN', symbol: 'WOMEN', label: 'WomenCoin' },
  { id: 'coin_ICE', symbol: 'ICE', label: 'iDice' },
  { id: 'coin_XLR', symbol: 'XLR', label: 'Solaris' },
  { id: 'coin_PAK', symbol: 'PAK', label: 'Pakcoin' },
  { id: 'coin_BITS', symbol: 'BITS', label: 'Bitstar' },
  { id: 'coin_ATOM', symbol: 'ATOM', label: 'Atomic Coin' },
  { id: 'coin_TIT', symbol: 'TIT', label: 'Titcoin' },
  { id: 'coin_SWING', symbol: 'SWING', label: 'Swing' },
  { id: 'coin_BITBTC', symbol: 'BITBTC', label: 'bitBTC' },
  { id: 'coin_DSH', symbol: 'DSH', label: 'Dashcoin' },
  { id: 'coin_XPTX', symbol: 'XPTX', label: 'PlatinumBAR' },
  { id: 'coin_BLN', symbol: 'BLN', label: 'Bolenum' },
  { id: 'coin_HODL', symbol: 'HODL', label: 'HOdlcoin' },
  { id: 'coin_MOJO', symbol: 'MOJO', label: 'MojoCoin' },
  { id: 'coin_FRN', symbol: 'FRN', label: 'Francs' },
  { id: 'coin_ITZ', symbol: 'ITZ', label: 'Interzone' },
  { id: 'coin_XCS', symbol: 'XCS', label: 'CybCSec' },
  { id: 'coin_SHDW', symbol: 'SHDW', label: 'Shadow Token' },
  { id: 'coin_DLC', symbol: 'DLC', label: 'Dollarcoin' },
  { id: 'coin_XCXT', symbol: 'XCXT', label: 'CoinonatX' },
  { id: 'coin_FLT', symbol: 'FLT', label: 'FlutterCoin' },
  { id: 'coin_PR', symbol: 'PR', label: 'Prototanium' },
  { id: 'coin_EL', symbol: 'EL', label: 'Elcoin' },
  { id: 'coin_MAY', symbol: 'MAY', label: 'Theresa May Coin' },
  { id: 'coin_RUPX', symbol: 'RUPX', label: 'Rupaya' },
  { id: 'coin_RBX', symbol: 'RBX', label: 'Ripto Bux' },
  { id: 'coin_FC2', symbol: 'FC2', label: 'FuelCoin' },
  { id: 'coin_BTWTY', symbol: 'BTWTY', label: 'Bit20' },
  { id: 'coin_LANA', symbol: 'LANA', label: 'LanaCoin' },
  { id: 'coin_BRIA', symbol: 'BRIA', label: 'BriaCoin' },
  { id: 'coin_XRA', symbol: 'XRA', label: 'Ratecoin' },
  { id: 'coin_BOLI', symbol: 'BOLI', label: 'Bolivarcoin' },
  { id: 'coin_BBP', symbol: 'BBP', label: 'BiblePay' },
  { id: 'coin_CCN', symbol: 'CCN', label: 'Cannacoin' },
  { id: 'coin_DRACO', symbol: 'DRACO', label: 'DT Token' },
  { id: 'coin_TEK', symbol: 'TEK', label: 'TEKcoin' },
  { id: 'coin_CTO', symbol: 'CTO', label: 'Crypto' },
  { id: 'coin_BITSILVER', symbol: 'BITSILVER', label: 'bitSilver' },
  { id: 'coin_VUC', symbol: 'VUC', label: 'Virta Unique ...' },
  { id: 'coin_LTB', symbol: 'LTB', label: 'LiteBar' },
  { id: 'coin_XCO', symbol: 'XCO', label: 'X-Coin' },
  { id: 'coin_PXI', symbol: 'PXI', label: 'Prime-XI' },
  { id: 'coin_SLM', symbol: 'SLM', label: 'Slimcoin' },
  { id: 'coin_REE', symbol: 'REE', label: 'ReeCoin' },
  { id: 'coin_UNITS', symbol: 'UNITS', label: 'GameUnits' },
  { id: 'coin_ZNY', symbol: 'ZNY', label: 'Bitzeny' },
  { id: 'coin_BLC', symbol: 'BLC', label: 'Blakecoin' },
  { id: 'coin_BSTY', symbol: 'BSTY', label: 'GlobalBoost-Y' },
  { id: 'coin_XCT', symbol: 'XCT', label: 'C-Bit' },
  { id: 'coin_XJO', symbol: 'XJO', label: 'Joulecoin' },
  { id: 'coin_ECO', symbol: 'ECO', label: 'EcoCoin' },
  { id: 'coin_QCN', symbol: 'QCN', label: 'QuazarCoin' },
  { id: 'coin_YAC', symbol: 'YAC', label: 'Yacoin' },
  { id: 'coin_CON', symbol: 'CON', label: 'PayCon' },
  { id: 'coin_BTPL', symbol: 'BTPL', label: 'Bitcoin Planet' },
  { id: 'coin_PRC', symbol: 'PRC', label: 'PRCoin' },
  { id: 'coin_STV', symbol: 'STV', label: 'Sativacoin' },
  { id: 'coin_DRXNE', symbol: 'DRXNE', label: 'DROXNE' },
  { id: 'coin_BITEUR', symbol: 'BITEUR', label: 'bitEUR' },
  { id: 'coin_TIX', symbol: 'TIX', label: 'Tickets' },
  { id: 'coin_GPU', symbol: 'GPU', label: 'GPU Coin' },
  { id: 'coin_GCC', symbol: 'GCC', label: 'GuccioneCoin' },
  { id: 'coin_ADCN', symbol: 'ADCN', label: 'Asiadigicoin' },
  { id: 'coin_ASAFE2', symbol: 'ASAFE2', label: 'AllSafe' },
  { id: 'coin_TTC', symbol: 'TTC', label: 'TittieCoin' },
  { id: 'coin_WORM', symbol: 'WORM', label: 'HealthyWormCoin' },
  { id: 'coin_KURT', symbol: 'KURT', label: 'Kurrent' },
  { id: 'coin_RBT', symbol: 'RBT', label: 'Rimbit' },
  { id: 'coin_XTC', symbol: 'XTC', label: 'TileCoin' },
  { id: 'coin_BIP', symbol: 'BIP', label: 'BipCoin' },
  { id: 'coin_CMPCO', symbol: 'CMPCO', label: 'CampusCoin' },
  { id: 'coin_MSCN', symbol: 'MSCN', label: 'Master Swiscoin' },
  { id: 'coin_AMMO', symbol: 'AMMO', label: 'Ammo Rewards' },
  { id: 'coin_VLTC', symbol: 'VLTC', label: 'Vault Coin' },
  { id: 'coin_LCP', symbol: 'LCP', label: 'Litecoin Plus' },
  { id: 'coin_NEVA', symbol: 'NEVA', label: 'NevaCoin' },
  { id: 'coin_KRONE', symbol: 'KRONE', label: 'Kronecoin' },
  { id: 'coin_CTIC2', symbol: 'CTIC2', label: 'Coimatic 2.0' },
  { id: 'coin_BSTAR', symbol: 'BSTAR', label: 'Blackstar' },
  { id: 'coin_VRS', symbol: 'VRS', label: 'Veros' },
  { id: 'coin_CREVA', symbol: 'CREVA', label: 'CrevaCoin' },
  { id: 'coin_TAJ', symbol: 'TAJ', label: 'TajCoin' },
  { id: 'coin_JIO', symbol: 'JIO', label: 'JIO Token' },
  { id: 'coin_ACP', symbol: 'ACP', label: 'AnarchistsPrime' },
  { id: 'coin_WBC', symbol: 'WBC', label: 'WalletBuilder...' },
  { id: 'coin_SFC', symbol: 'SFC', label: 'Solarflarecoin' },
  { id: 'coin_LTCU', symbol: 'LTCU', label: 'LiteCoin Ultra' },
  { id: 'coin_CNC', symbol: 'CNC', label: 'CHNCoin' },
  { id: 'coin_WEX', symbol: 'WEX', label: 'Wexcoin' },
  { id: 'coin_KNC', symbol: 'KNC', label: 'KingN Coin' },
  { id: 'coin_ALTC', symbol: 'ALTC', label: 'Antilitecoin' },
  { id: 'coin_LVPS', symbol: 'LVPS', label: 'LevoPlus' },
  { id: 'coin_LBTC', symbol: 'LBTC', label: 'LiteBitcoin' },
  { id: 'coin_EBT', symbol: 'EBT', label: 'Ebittree Coin' },
  { id: 'coin_NODC', symbol: 'NODC', label: 'NodeCoin' },
  { id: 'coin_XNG', symbol: 'XNG', label: 'Enigma' },
  { id: 'coin_CF', symbol: 'CF', label: 'Californium' },
  { id: 'coin_HMC', symbol: 'HMC', label: 'HarmonyCoin' },
  { id: 'coin_DMB', symbol: 'DMB', label: 'Digital Money...' },
  { id: 'coin_APW', symbol: 'APW', label: 'AppleCoin' },
  { id: 'coin_ADK', symbol: 'ADK', label: 'Aidos Kuneen' },
  { id: 'coin_ROUND', symbol: 'ROUND', label: 'Round' },
  { id: 'coin_BPC', symbol: 'BPC', label: 'Bitpark Coin' },
  { id: 'coin_GRE', symbol: 'GRE', label: 'Greencoin' },
  { id: 'coin_BITZ', symbol: 'BITZ', label: 'Bitz' },
  { id: 'coin_YASH', symbol: 'YASH', label: 'YashCoin' },
  { id: 'coin_AC', symbol: 'AC', label: 'AsiaCoin' },
  { id: 'coin_ADL', symbol: 'ADL', label: 'Adelphoi' },
  { id: 'coin_INPAY', symbol: 'INPAY', label: 'InPay' },
  { id: 'coin_ARC', symbol: 'ARC', label: 'Arcade Token' },
  { id: 'coin_QRK', symbol: 'QRK', label: 'Quark' },
  { id: 'coin_EAC', symbol: 'EAC', label: 'EarthCoin' },
  { id: 'coin_FYN', symbol: 'FYN', label: 'FundYourselfNow' },
  { id: 'coin_CV2', symbol: 'CV2', label: 'Colossuscoin V2' },
  { id: 'coin_CRYPT', symbol: 'CRYPT', label: 'CryptCoin' },
  { id: 'coin_ALT', symbol: 'ALT', label: 'Altcoin' },
  { id: 'coin_LOG', symbol: 'LOG', label: 'Woodcoin' },
  { id: 'coin_IXC', symbol: 'IXC', label: 'Ixcoin' },
  { id: 'coin_IFLT', symbol: 'IFLT', label: 'InflationCoin' },
  { id: 'coin_USC', symbol: 'USC', label: 'Ultimate Secu...' },
  { id: 'coin_FIMK', symbol: 'FIMK', label: 'FIMKrypto' },
  { id: 'coin_METAL', symbol: 'METAL', label: 'MetalCoin' },
  { id: 'coin_MAX', symbol: 'MAX', label: 'MaxCoin' },
  { id: 'coin_SMC', symbol: 'SMC', label: 'SmartCoin' },
  { id: 'coin_TOKEN', symbol: 'TOKEN', label: 'SwapToken' },
  { id: 'coin_ZET', symbol: 'ZET', label: 'Zetacoin' },
  { id: 'coin_CARBON', symbol: 'CARBON', label: 'Carboncoin' },
  { id: 'coin_SDC', symbol: 'SDC', label: 'ShadowCash' },
  { id: 'coin_HERO', symbol: 'HERO', label: 'Sovereign Hero' },
  { id: 'coin_FNC', symbol: 'FNC', label: 'FinCoin' },
  { id: 'coin_NKA', symbol: 'NKA', label: 'IncaKoin' },
  { id: 'coin_ITI', symbol: 'ITI', label: 'iTicoin' },
  { id: 'coin_E4ROW', symbol: 'E4ROW', label: 'E4ROW' },
  { id: 'coin_CASINO', symbol: 'CASINO', label: 'Casino' },
  { id: 'coin_RC', symbol: 'RC', label: 'RussiaCoin' },
  { id: 'coin_SHORTY', symbol: 'SHORTY', label: 'Shorty' },
  { id: 'coin_MBI', symbol: 'MBI', label: 'Monster Byte' },
  { id: 'coin_UFO', symbol: 'UFO', label: 'UFO Coin' },
  { id: 'coin_DFT', symbol: 'DFT', label: 'DraftCoin' },
  { id: 'coin_CDN', symbol: 'CDN', label: 'Canada eCoin' },
  { id: 'coin_SUPER', symbol: 'SUPER', label: 'SuperCoin' },
  { id: 'coin_UTC', symbol: 'UTC', label: 'UltraCoin' },
  { id: 'coin_TAG', symbol: 'TAG', label: 'TagCoin' },
  { id: 'coin_RIYA', symbol: 'RIYA', label: 'Etheriya' },
  { id: 'coin_BTB', symbol: 'BTB', label: 'BitBar' },
  { id: 'coin_UNIT', symbol: 'UNIT', label: 'Universal Cur...' },
  { id: 'coin_TROLL', symbol: 'TROLL', label: 'Trollcoin' },
  { id: 'coin_BTSR', symbol: 'BTSR', label: 'BTSR' },
  { id: 'coin_AMBER', symbol: 'AMBER', label: 'AmberCoin' },
  { id: 'coin_XCN', symbol: 'XCN', label: 'Cryptonite' },
  { id: 'coin_HBN', symbol: 'HBN', label: 'HoboNickels' },
  { id: 'coin_GLC', symbol: 'GLC', label: 'GlobalCoin' },
  { id: 'coin_MZC', symbol: 'MZC', label: 'MazaCoin' },
  { id: 'coin_ANC', symbol: 'ANC', label: 'Anoncoin' },
  { id: 'coin_I0C', symbol: 'I0C', label: 'I0Coin' },
  { id: 'coin_ORB', symbol: 'ORB', label: 'Orbitcoin' },
  { id: 'coin_PXC', symbol: 'PXC', label: 'Phoenixcoin' },
  { id: 'coin_GCN', symbol: 'GCN', label: 'GCoin' },
  { id: 'coin_DVC', symbol: 'DVC', label: 'Devcoin' },
  { id: 'coin_PIGGY', symbol: 'PIGGY', label: 'Piggycoin' },
  { id: 'coin_GOOD', symbol: 'GOOD', label: 'Goodomy' },
  { id: 'coin_GAIA', symbol: 'GAIA', label: 'GAIA' },
  { id: 'coin_OHM', symbol: 'OHM', label: 'OHM' },
  { id: 'coin_AU', symbol: 'AU', label: 'AurumCoin' },
  { id: 'coin_8BIT', symbol: '8BIT', label: '8Bit' },
  { id: 'coin_TALK', symbol: 'TALK', label: 'BTCtalkcoin' },
  { id: 'coin_BLOCKPAY', symbol: 'BLOCKPAY', label: 'BlockPay' },
  { id: 'coin_WYV', symbol: 'WYV', label: 'Wyvern' },
  { id: 'coin_XPY', symbol: 'XPY', label: 'PayCoin' },
  { id: 'coin_STS', symbol: 'STS', label: 'Stress' },
  { id: 'coin_KRS', symbol: 'KRS', label: 'Krypstal' },
  { id: 'coin_BTCS', symbol: 'BTCS', label: 'Bitcoin Scrypt' },
  { id: 'coin_PSB', symbol: 'PSB', label: 'Pesobit' },
  { id: 'coin_MNM', symbol: 'MNM', label: 'Mineum' },
  { id: 'coin_CAGE', symbol: 'CAGE', label: 'CageCoin' },
  { id: 'coin_OPAL', symbol: 'OPAL', label: 'Opal' },
  { id: 'coin_V', symbol: 'V', label: 'Version' },
  { id: 'coin_CFT', symbol: 'CFT', label: 'CryptoForecast' },
  { id: 'coin_KED', symbol: 'KED', label: 'Darsek' },
  { id: 'coin_TRK', symbol: 'TRK', label: 'Truckcoin' },
  { id: 'coin_UNI', symbol: 'UNI', label: 'Universe' },
  { id: 'coin_CNO', symbol: 'CNO', label: 'Coin(O)' },
  { id: 'coin_USDE', symbol: 'USDE', label: 'USDe' },
  { id: 'coin_ICN', symbol: 'ICN', label: 'iCoin' },
  { id: 'coin_VIDZ', symbol: 'VIDZ', label: 'PureVidz' },
  { id: 'coin_FLY', symbol: 'FLY', label: 'Flycoin' },
  { id: 'coin_SLG', symbol: 'SLG', label: 'Sterlingcoin' },
  { id: 'coin_FUNK', symbol: 'FUNK', label: 'The Cypherfunks' },
  { id: 'coin_WAY', symbol: 'WAY', label: 'WayGuide' },
  { id: 'coin_VAL', symbol: 'VAL', label: 'Valorbit' },
  { id: 'coin_CAP', symbol: 'CAP', label: 'Bottlecaps' },
  { id: 'coin_BUN', symbol: 'BUN', label: 'BunnyCoin' },
  { id: 'coin_JIN', symbol: 'JIN', label: 'Jin Coin' },
  { id: 'coin_UNIC', symbol: 'UNIC', label: 'UniCoin' },
  { id: 'coin_DGC', symbol: 'DGC', label: 'Digitalcoin' },
  { id: 'coin_NYAN', symbol: 'NYAN', label: 'Nyancoin' },
  { id: 'coin_LOT', symbol: 'LOT', label: 'LottoCoin' },
  { id: 'coin_HONEY', symbol: 'HONEY', label: 'Honey' },
  { id: 'coin_KUSH', symbol: 'KUSH', label: 'KushCoin' },
  { id: 'coin_XGR', symbol: 'XGR', label: 'GoldReserve' },
  { id: 'coin_CYP', symbol: 'CYP', label: 'Cypher' },
  { id: 'coin_BERN', symbol: 'BERN', label: 'BERNcash' },
  { id: 'coin_FRC', symbol: 'FRC', label: 'Freicoin' },
  { id: 'coin_CJ', symbol: 'CJ', label: 'Cryptojacks' },
  { id: 'coin_Q2C', symbol: 'Q2C', label: 'QubitCoin' },
  { id: 'coin_CHESS', symbol: 'CHESS', label: 'ChessCoin' },
  { id: 'coin_CUBE', symbol: 'CUBE', label: 'DigiCube' },
  { id: 'coin_EMD', symbol: 'EMD', label: 'Emerald Crypto' },
  { id: 'coin_KLC', symbol: 'KLC', label: 'KiloCoin' },
  { id: 'coin_SAC', symbol: 'SAC', label: 'SACoin' },
  { id: 'coin_XRE', symbol: 'XRE', label: 'RevolverCoin' },
  { id: 'coin_PUTIC', symbol: 'PUTIC', label: 'Putin Classic' },
  { id: 'coin_SPEX', symbol: 'SPEX', label: 'SproutsExtreme' },
  { id: 'coin_BTCR', symbol: 'BTCR', label: 'Bitcurrency' },
  { id: 'coin_GP', symbol: 'GP', label: 'GoldPieces' },
  { id: 'coin_GUN', symbol: 'GUN', label: 'Guncoin' },
  { id: 'coin_J', symbol: 'J', label: 'Joincoin' },
  { id: 'coin_GB', symbol: 'GB', label: 'GoldBlocks' },
  { id: 'coin_BXT', symbol: 'BXT', label: 'BitTokens' },
  { id: 'coin_TGC', symbol: 'TGC', label: 'Tigercoin' },
  { id: 'coin_ACOIN', symbol: 'ACOIN', label: 'Acoin' },
  { id: 'coin_GRT', symbol: 'GRT', label: 'Grantcoin' },
  { id: 'coin_CNNC', symbol: 'CNNC', label: 'Cannation' },
  { id: 'coin_C2', symbol: 'C2', label: 'Coin2.1' },
  { id: 'coin_BAS', symbol: 'BAS', label: 'BitAsean' },
  { id: 'coin_BIGUP', symbol: 'BIGUP', label: 'BigUp' },
  { id: 'coin_MCRN', symbol: 'MCRN', label: 'MACRON' },
  { id: 'coin_FLAX', symbol: 'FLAX', label: 'Flaxscript' },
  { id: 'coin_BITGOLD', symbol: 'BITGOLD', label: 'bitGold' },
  { id: 'coin_XPD', symbol: 'XPD', label: 'PetroDollar' },
  { id: 'coin_FUNC', symbol: 'FUNC', label: 'FUNCoin' },
  { id: 'coin_SMOKE', symbol: 'SMOKE', label: 'Smoke' },
  { id: 'coin_ELE', symbol: 'ELE', label: 'Elementrem' },
  { id: 'coin_ZUR', symbol: 'ZUR', label: 'Zurcoin' },
  { id: 'coin_TSE', symbol: 'TSE', label: 'Tattoocoin (S...' },
  { id: 'coin_EVO', symbol: 'EVO', label: 'Evotion' },
  { id: 'coin_EVIL', symbol: 'EVIL', label: 'Evil Coin' },
  { id: 'coin_MAD', symbol: 'MAD', label: 'SatoshiMadness' },
  { id: 'coin_NDAO', symbol: 'NDAO', label: 'NeuroDAO' },
  { id: 'coin_KIC', symbol: 'KIC', label: 'KibiCoin' },
  { id: 'coin_PASL', symbol: 'PASL', label: 'Pascal Lite' },
  { id: 'coin_WMC', symbol: 'WMC', label: 'WMCoin' },
  { id: 'coin_TOR', symbol: 'TOR', label: 'Torcoin' },
  { id: 'coin_FRK', symbol: 'FRK', label: 'Franko' },
  { id: 'coin_CACH', symbol: 'CACH', label: 'CacheCoin' },
  { id: 'coin_ANTI', symbol: 'ANTI', label: 'AntiBitcoin' },
  { id: 'coin_LTBC', symbol: 'LTBC', label: 'LTBcoin' },
  { id: 'coin_ARCO', symbol: 'ARCO', label: 'AquariusCoin' },
  { id: 'coin_BCF', symbol: 'BCF', label: 'BitcoinFast' },
  { id: 'coin_XBTC21', symbol: 'XBTC21', label: 'Bitcoin 21' },
  { id: 'coin_888', symbol: '888', label: 'OctoCoin' },
  { id: 'coin_020', symbol: '020', label: '020LondonCoin' },
  { id: 'coin_CORG', symbol: 'CORG', label: 'CorgiCoin' },
  { id: 'coin_SPACE', symbol: 'SPACE', label: 'SpaceCoin' },
  { id: 'coin_CAT', symbol: 'CAT', label: 'Catcoin' },
  { id: 'coin_ARG', symbol: 'ARG', label: 'Argentum' },
  { id: 'coin_DUO', symbol: 'DUO', label: 'ParallelCoin' },
  { id: 'coin_CRX', symbol: 'CRX', label: 'Chronos' },
  { id: 'coin_GLT', symbol: 'GLT', label: 'GlobalToken' },
  { id: 'coin_SRC', symbol: 'SRC', label: 'SecureCoin' },
  { id: 'coin_DRM', symbol: 'DRM', label: 'Dreamcoin' },
  { id: 'coin_MARS', symbol: 'MARS', label: 'Marscoin' },
  { id: 'coin_ARI', symbol: 'ARI', label: 'Aricoin' },
  { id: 'coin_GAP', symbol: 'GAP', label: 'Gapcoin' },
  { id: 'coin_SPT', symbol: 'SPT', label: 'Spots' },
  { id: 'coin_300', symbol: '300', label: '300 Token' },
  { id: 'coin_MTM', symbol: 'MTM', label: 'MTMGaming' },
  { id: 'coin_HMP', symbol: 'HMP', label: 'HempCoin' },
  { id: 'coin_FIRE', symbol: 'FIRE', label: 'Firecoin' },
  { id: 'coin_ARB', symbol: 'ARB', label: 'ARbit' },
  { id: 'coin_DIBC', symbol: 'DIBC', label: 'DIBCOIN' },
  { id: 'coin_VEC2', symbol: 'VEC2', label: 'Vector' },
  { id: 'coin_MST', symbol: 'MST', label: 'MustangCoin' },
  { id: 'coin_PX', symbol: 'PX', label: 'PX' },
  { id: 'coin_PONZI', symbol: 'PONZI', label: 'PonziCoin' },
  { id: 'coin_URC', symbol: 'URC', label: 'Unrealcoin' },
  { id: 'coin_COXST', symbol: 'COXST', label: 'CoExistCoin' },
  { id: 'coin_RED', symbol: 'RED', label: 'RedCoin' },
  { id: 'coin_BUMBA', symbol: 'BUMBA', label: 'BumbaCoin' },
  { id: 'coin_GTC', symbol: 'GTC', label: 'Global Tour Coin' },
  { id: 'coin_EUC', symbol: 'EUC', label: 'Eurocoin' },
  { id: 'coin_SLING', symbol: 'SLING', label: 'Sling' },
  { id: 'coin_TSTR', symbol: 'TSTR', label: 'Tristar Coin' },
  { id: 'coin_QTL', symbol: 'QTL', label: 'Quatloo' },
  { id: 'coin_DBTC', symbol: 'DBTC', label: 'Debitcoin' },
  { id: 'coin_ISL', symbol: 'ISL', label: 'IslaCoin' },
  { id: 'coin_SCRT', symbol: 'SCRT', label: 'SecretCoin' },
  { id: 'coin_ICOB', symbol: 'ICOB', label: 'ICOBID' },
  { id: 'coin_WARP', symbol: 'WARP', label: 'WARP' },
  { id: 'coin_AGLC', symbol: 'AGLC', label: 'AgrolifeCoin' },
  { id: 'coin_BLRY', symbol: 'BLRY', label: 'BillaryCoin' },
  { id: 'coin_HAL', symbol: 'HAL', label: 'Halcyon' },
  { id: 'coin_IMS', symbol: 'IMS', label: 'Independent M...' },
  { id: 'coin_VC', symbol: 'VC', label: 'VirtualCoin' },
  { id: 'coin_SOIL', symbol: 'SOIL', label: 'SOILcoin' },
  { id: 'coin_CXT', symbol: 'CXT', label: 'Coinonat' },
  { id: 'coin_4CHN', symbol: '4CHN', label: 'ChanCoin' },
  { id: 'coin_URO', symbol: 'URO', label: 'Uro' },
  { id: 'coin_611', symbol: '611', label: 'SixEleven' },
  { id: 'coin_BOST', symbol: 'BOST', label: 'BoostCoin' },
  { id: 'coin_PHS', symbol: 'PHS', label: 'Philosopher S...' },
  { id: 'coin_HKG', symbol: 'HKG', label: 'Hacker Gold' },
  { id: 'coin_FLVR', symbol: 'FLVR', label: 'FlavorCoin' },
  { id: 'coin_BRAIN', symbol: 'BRAIN', label: 'Braincoin' },
  { id: 'coin_ALL', symbol: 'ALL', label: 'Allion' },
  { id: 'coin_MAR', symbol: 'MAR', label: 'Marijuanacoin' },
  { id: 'coin_MND', symbol: 'MND', label: 'MindCoin' },
  { id: 'coin_ERY', symbol: 'ERY', label: 'Eryllium' },
  { id: 'coin_GPL', symbol: 'GPL', label: 'Gold Pressed ...' },
  { id: 'coin_CPN', symbol: 'CPN', label: 'CompuCoin' },
  { id: 'coin_ZYD', symbol: 'ZYD', label: 'Zayedcoin' },
  { id: 'coin_MEOW', symbol: 'MEOW', label: 'Kittehcoin' },
  { id: 'coin_MILO', symbol: 'MILO', label: 'MiloCoin' },
  { id: 'coin_HXX', symbol: 'HXX', label: 'Hexx' },
  { id: 'coin_DES', symbol: 'DES', label: 'Destiny' },
  { id: 'coin_TRADE', symbol: 'TRADE', label: 'Tradecoin' },
  { id: 'coin_JOBS', symbol: 'JOBS', label: 'JobsCoin' },
  { id: 'coin_NRO', symbol: 'NRO', label: 'Neuro' },
  { id: 'coin_BENJI', symbol: 'BENJI', label: 'BenjiRolls' },
  { id: 'coin_CESC', symbol: 'CESC', label: 'CryptoEscudo' },
  { id: 'coin_SOON', symbol: 'SOON', label: 'SoonCoin' },
  { id: 'coin_G3N', symbol: 'G3N', label: 'G3N' },
  { id: 'coin_PRX', symbol: 'PRX', label: 'Printerium' },
  { id: 'coin_STEPS', symbol: 'STEPS', label: 'Steps' },
  { id: 'coin_$$$', symbol: '$$$', label: 'Money' },
  { id: 'coin_BVC', symbol: 'BVC', label: 'BeaverCoin' },
  { id: 'coin_CMT', symbol: 'CMT', label: 'Comet' },
  { id: 'coin_XCRE', symbol: 'XCRE', label: 'Creatio' },
  { id: 'coin_ATX', symbol: 'ATX', label: 'Artex Coin' },
  { id: 'coin_RPC', symbol: 'RPC', label: 'RonPaulCoin' },
  { id: 'coin_PLNC', symbol: 'PLNC', label: 'PLNcoin' },
  { id: 'coin_BIOS', symbol: 'BIOS', label: 'BiosCrypto' },
  { id: 'coin_QBK', symbol: 'QBK', label: 'Qibuck Asset' },
  { id: 'coin_POP', symbol: 'POP', label: 'PopularCoin' },
  { id: 'coin_ICON', symbol: 'ICON', label: 'Iconic' },
  { id: 'coin_JWL', symbol: 'JWL', label: 'Jewels' },
  { id: 'coin_COAL', symbol: 'COAL', label: 'BitCoal' },
  { id: 'coin_PHO', symbol: 'PHO', label: 'Photon' },
  { id: 'coin_ZMC', symbol: 'ZMC', label: 'ZetaMicron' },
  { id: 'coin_LEA', symbol: 'LEA', label: 'LeaCoin' },
  { id: 'coin_GBT', symbol: 'GBT', label: 'GameBet Coin' },
  { id: 'coin_BOAT', symbol: 'BOAT', label: 'Doubloon' },
  { id: 'coin_GBC', symbol: 'GBC', label: 'GBCGoldCoin' },
  { id: 'coin_UET', symbol: 'UET', label: 'Useless Ether...' },
  { id: 'coin_BTQ', symbol: 'BTQ', label: 'BitQuark' },
  { id: 'coin_ORLY', symbol: 'ORLY', label: 'Orlycoin' },
  { id: 'coin_LUNA', symbol: 'LUNA', label: 'Luna Coin' },
  { id: 'coin_LTCR', symbol: 'LTCR', label: 'Litecred' },
  { id: 'coin_XBTS', symbol: 'XBTS', label: 'Beatcoin' },
  { id: 'coin_IMX', symbol: 'IMX', label: 'Impact' },
  { id: 'coin_DRS', symbol: 'DRS', label: 'Digital Rupees' },
  { id: 'coin_RIDE', symbol: 'RIDE', label: 'Ride My Car' },
  { id: 'coin_FRAZ', symbol: 'FRAZ', label: 'Frazcoin' },
  { id: 'coin_OFF', symbol: 'OFF', label: 'Cthulhu Offer...' },
  { id: 'coin_MTLMC3', symbol: 'MTLMC3', label: 'Metal Music Coin' },
  { id: 'coin_SONG', symbol: 'SONG', label: 'SongCoin' },
  { id: 'coin_BSC', symbol: 'BSC', label: 'BowsCoin' },
  { id: 'coin_DLISK', symbol: 'DLISK', label: 'DAPPSTER' },
  { id: 'coin_FUZZ', symbol: 'FUZZ', label: 'FuzzBalls' },
  { id: 'coin_TAGR', symbol: 'TAGR', label: 'TAGRcoin' },
  { id: 'coin_SOCC', symbol: 'SOCC', label: 'SocialCoin' },
  { id: 'coin_BLZ', symbol: 'BLZ', label: 'BlazeCoin' },
  { id: 'coin_CRT', symbol: 'CRT', label: 'CRTCoin' },
  { id: 'coin_VTA', symbol: 'VTA', label: 'Virtacoin' },
  { id: 'coin_EGO', symbol: 'EGO', label: 'EGO' },
  { id: 'coin_CASH', symbol: 'CASH', label: 'Cashcoin' },
  { id: 'coin_PEX', symbol: 'PEX', label: 'PosEx' },
  { id: 'coin_CONX', symbol: 'CONX', label: 'Concoin' },
  { id: 'coin_1CR', symbol: '1CR', label: '1CRedit' },
  { id: 'coin_SANDG', symbol: 'SANDG', label: 'Save and Gain' },
  { id: 'coin_HVCO', symbol: 'HVCO', label: 'High Voltage' },
  { id: 'coin_DPAY', symbol: 'DPAY', label: 'DPAY' },
  { id: 'coin_IMPS', symbol: 'IMPS', label: 'ImpulseCoin' },
  { id: 'coin_LIR', symbol: 'LIR', label: 'LetItRide' },
  { id: 'coin_BIOB', symbol: 'BIOB', label: 'BioBar' },
  { id: 'coin_SLEVIN', symbol: 'SLEVIN', label: 'Slevin' },
  { id: 'coin_OS76', symbol: 'OS76', label: 'OsmiumCoin' },
  { id: 'coin_CAB', symbol: 'CAB', label: 'Cabbage' },
  { id: 'coin_ZNE', symbol: 'ZNE', label: 'Zonecoin' },
  { id: 'coin_RSGP', symbol: 'RSGP', label: 'RSGPcoin' },
  { id: 'coin_SH', symbol: 'SH', label: 'Shilling' },
  { id: 'coin_IBANK', symbol: 'IBANK', label: 'iBank' },
  { id: 'coin_SCS', symbol: 'SCS', label: 'Speedcash' },
  { id: 'coin_VIP', symbol: 'VIP', label: 'VIP Tokens' },
  { id: 'coin_XOC', symbol: 'XOC', label: 'Xonecoin' },
  { id: 'coin_DOLLAR', symbol: 'DOLLAR', label: 'Dollar Online' },
  { id: 'coin_MGM', symbol: 'MGM', label: 'Magnum' },
  { id: 'coin_NANOX', symbol: 'NANOX', label: 'Project-X' },
  { id: 'coin_VPRC', symbol: 'VPRC', label: 'VapersCoin' },
  { id: 'coin_BNX', symbol: 'BNX', label: 'BnrtxCoin' },
  { id: 'coin_REV', symbol: 'REV', label: 'Revenu' },
  { id: 'coin_CCM100', symbol: 'CCM100', label: 'CCMiner' },
  { id: 'coin_SDP', symbol: 'SDP', label: 'SydPak' },
  { id: 'coin_VOLT', symbol: 'VOLT', label: 'Bitvolt' },
  { id: 'coin_ARGUS', symbol: 'ARGUS', label: 'Argus' },
  { id: 'coin_GEERT', symbol: 'GEERT', label: 'GeertCoin' },
  { id: 'coin_XRC', symbol: 'XRC', label: 'Rawcoin' },
  { id: 'coin_P7C', symbol: 'P7C', label: 'P7Coin' },
  { id: 'coin_DIX', symbol: 'DIX', label: 'Dix Asset' },
  { id: 'coin_ELS', symbol: 'ELS', label: 'Elysium' },
  { id: 'coin_PULSE', symbol: 'PULSE', label: 'Pulse' },
  { id: 'coin_SLFI', symbol: 'SLFI', label: 'Selfiecoin' },
  { id: 'coin_MNC', symbol: 'MNC', label: 'MantraCoin' },
  { id: 'coin_OCEAN', symbol: 'OCEAN', label: 'BurstOcean' },
  { id: 'coin_SOJ', symbol: 'SOJ', label: 'Sojourn' },
  { id: 'coin_LEX', symbol: 'LEX', label: 'Lex4All' },
  { id: 'coin_PIZZA', symbol: 'PIZZA', label: 'PizzaCoin' },
  { id: 'coin_DRAGON', symbol: 'DRAGON', label: 'BTCDragon' },
  { id: 'coin_BQC', symbol: 'BQC', label: 'BBQCoin' },
  { id: 'coin_PWR', symbol: 'PWR', label: 'Powercoin' },
  { id: 'coin_FDC', symbol: 'FDC', label: 'Future Digita...' },
  { id: 'coin_ULA', symbol: 'ULA', label: 'Ulatech' },
  { id: 'coin_MUG', symbol: 'MUG', label: 'MikeTheMug' },
  { id: 'coin_DGCS', symbol: 'DGCS', label: 'Digital Credits' },
  { id: 'coin_ABN', symbol: 'ABN', label: 'Abncoin' },
  { id: 'coin_ENV', symbol: 'ENV', label: 'Environ' },
  { id: 'coin_XEN', symbol: 'XEN', label: 'Xenixcoin' },
  { id: 'coin_CALC', symbol: 'CALC', label: 'CaliphCoin' },
  { id: 'coin_GBG', symbol: 'GBG', label: 'Golos Gold' },
  { id: 'coin_INF', symbol: 'INF', label: 'InfChain' },
  { id: 'coin_FRGC', symbol: 'FRGC', label: 'Fargocoin' },
  { id: 'coin_ENG', symbol: 'ENG', label: 'Enigma' },
  { id: 'coin_DMC', symbol: 'DMC', label: 'DynamicCoin' },
  { id: 'coin_XTZ', symbol: 'XTZ', label: 'Tezos (Pre-La...' },
  { id: 'coin_ACT', symbol: 'ACT', label: 'Achain' },
  { id: 'coin_FLIK', symbol: 'FLIK', label: 'FLiK' },
  { id: 'coin_KLN', symbol: 'KLN', label: 'Kolion' },
  { id: 'coin_CNX', symbol: 'CNX', label: 'Cryptonex' },
  { id: 'coin_EBST', symbol: 'EBST', label: 'eBoost' },
  { id: 'coin_MSD', symbol: 'MSD', label: 'MSD' },
  { id: 'coin_XIN', symbol: 'XIN', label: 'Infinity Econ...' },
  { id: 'coin_CLUB', symbol: 'CLUB', label: 'ClubCoin' },
  { id: 'coin_TER', symbol: 'TER', label: 'TerraNova' },
  { id: 'coin_XID', symbol: 'XID', label: 'Sphre AIR' },
  { id: 'coin_XBG', symbol: 'XBG', label: 'BTCGold' },
  { id: 'coin_ORME', symbol: 'ORME', label: 'Ormeus Coin' },
  { id: 'coin_SJCX', symbol: 'SJCX', label: 'Storjcoin X' },
  { id: 'coin_SDRN', symbol: 'SDRN', label: 'Senderon' },
  { id: 'coin_THS', symbol: 'THS', label: 'TechShares' },
  { id: 'coin_BQ', symbol: 'BQ', label: 'bitqy' },
  { id: 'coin_YOYOW', symbol: 'YOYOW', label: 'YOYOW' },
  { id: 'coin_CCT', symbol: 'CCT', label: 'Crystal Clear' },
  { id: 'coin_WHL', symbol: 'WHL', label: 'WhaleCoin' },
  { id: 'coin_AURS', symbol: 'AURS', label: 'Aureus' },
  { id: 'coin_REGA', symbol: 'REGA', label: 'Regacoin' },
  { id: 'coin_COB', symbol: 'COB', label: 'Cobinhood' },
  { id: 'coin_BTU', symbol: 'BTU', label: 'Bitcoin Unlim...' },
  { id: 'coin_BTDX', symbol: 'BTDX', label: 'Bitcloud' },
  { id: 'coin_IND', symbol: 'IND', label: 'Indorse Token' },
  { id: 'coin_RHOC', symbol: 'RHOC', label: 'RChain' },
  { id: 'coin_DEUS', symbol: 'DEUS', label: 'DeusCoin' },
  { id: 'coin_BUZZ', symbol: 'BUZZ', label: 'BuzzCoin' },
  { id: 'coin_UGT', symbol: 'UGT', label: 'UG Token' },
  { id: 'coin_YOC', symbol: 'YOC', label: 'Yocoin' },
  { id: 'coin_HGT', symbol: 'HGT', label: 'HelloGold' },
  { id: 'coin_GOKU', symbol: 'GOKU', label: 'Gokucoin' },
  { id: 'coin_SND', symbol: 'SND', label: 'Sand Coin' },
  { id: 'coin_BTCZ', symbol: 'BTCZ', label: 'BitcoinZ' },
  { id: 'coin_MCR', symbol: 'MCR', label: 'Macro' },
  { id: 'coin_SIGMA', symbol: 'SIGMA', label: 'SIGMAcoin' },
  { id: 'coin_DAY', symbol: 'DAY', label: 'Chronologic' },
  { id: 'coin_WA', symbol: 'WA', label: 'WA Space' },
  { id: 'coin_MBL', symbol: 'MBL', label: 'MobileCash' },
  { id: 'coin_FLASH', symbol: 'FLASH', label: 'Flash' },
  { id: 'coin_PCS', symbol: 'PCS', label: 'Pabyosi Coin ...' },
  { id: 'coin_SIFT', symbol: 'SIFT', label: 'Smart Investm...' },
  { id: 'coin_MG', symbol: 'MG', label: 'Mind Gene' },
  { id: 'coin_MGC', symbol: 'MGC', label: 'GulfCoin' },
  { id: 'coin_XID', symbol: 'XID', label: 'International...' },
  { id: 'coin_DFS', symbol: 'DFS', label: 'DFSCoin' },
  { id: 'coin_ETX', symbol: 'ETX', label: 'Etherx' },
  { id: 'coin_ACC', symbol: 'ACC', label: 'AdCoin' },
  { id: 'coin_MTNC', symbol: 'MTNC', label: 'Masternodecoin' },
  { id: 'coin_ELTC2', symbol: 'ELTC2', label: 'eLTC' },
  { id: 'coin_ETT', symbol: 'ETT', label: 'EncryptoTel [...' },
  { id: 'coin_STEX', symbol: 'STEX', label: 'STEX' },
  { id: 'coin_OX', symbol: 'OX', label: 'OX Fina' },
  { id: 'coin_GSR', symbol: 'GSR', label: 'GeyserCoin' },
  { id: 'coin_IQT', symbol: 'IQT', label: 'iQuant' },
  { id: 'coin_GRN', symbol: 'GRN', label: 'Granite' },
  { id: 'coin_GUC', symbol: 'GUC', label: 'GoldUnionCoin' },
  { id: 'coin_WILD', symbol: 'WILD', label: 'Wild Crypto' },
  { id: 'coin_XTD', symbol: 'XTD', label: 'XTD Coin' },
  { id: 'coin_ZBC', symbol: 'ZBC', label: 'Zilbercoin' },
  { id: 'coin_AMS', symbol: 'AMS', label: 'AmsterdamCoin' },
  { id: 'coin_ZENGOLD', symbol: 'ZENGOLD', label: 'ZenGold' },
  { id: 'coin_NAMO', symbol: 'NAMO', label: 'NamoCoin' },
  { id: 'coin_EFYT', symbol: 'EFYT', label: 'Ergo' },
  { id: 'coin_HNC', symbol: 'HNC', label: 'Huncoin' },
  { id: 'coin_PRIMU', symbol: 'PRIMU', label: 'Primulon' },
  { id: 'coin_TYC', symbol: 'TYC', label: 'Tyrocoin' },
  { id: 'coin_COLX', symbol: 'COLX', label: 'ColossusCoinXT' },
  { id: 'coin_MRJA', symbol: 'MRJA', label: 'GanjaCoin' },
  { id: 'coin_WIC', symbol: 'WIC', label: 'Wi Coin' },
  { id: 'coin_KEXCOIN', symbol: 'KEXCOIN', label: 'KexCoin' },
  { id: 'coin_BLAZR', symbol: 'BLAZR', label: 'BlazerCoin' },
  { id: 'coin_BET', symbol: 'BET', label: 'BetaCoin' },
  { id: 'coin_MEN', symbol: 'MEN', label: 'PeopleCoin' },
  { id: 'coin_KAYI', symbol: 'KAYI', label: 'Kayicoin' },
  { id: 'coin_INDIA', symbol: 'INDIA', label: 'India Coin' },
  { id: 'coin_LDCN', symbol: 'LDCN', label: 'LandCoin' },
  { id: 'coin_SUR', symbol: 'SUR', label: 'Suretly' },
  { id: 'coin_CYDER', symbol: 'CYDER', label: 'Cyder' },
  { id: 'coin_UR', symbol: 'UR', label: 'UR' },
  { id: 'coin_RUBIT', symbol: 'RUBIT', label: 'RubleBit' },
  { id: 'coin_BLX', symbol: 'BLX', label: 'Blockchain Index' },
  { id: 'coin_HALLO', symbol: 'HALLO', label: 'Halloween Coin' },
  { id: 'coin_UNRC', symbol: 'UNRC', label: 'UniversalRoya...' },
  { id: 'coin_ATMC', symbol: 'ATMC', label: 'ATMCoin' },
  { id: 'coin_FID', symbol: 'FID', label: 'BITFID' },
  { id: 'coin_BAT', symbol: 'BAT', label: 'BatCoin' },
  { id: 'coin_OP', symbol: 'OP', label: 'Operand' },
  { id: 'coin_MOTO', symbol: 'MOTO', label: 'Motocoin' },
  { id: 'coin_XLC', symbol: 'XLC', label: 'LeviarCoin' },
  { id: 'coin_MRNG', symbol: 'MRNG', label: 'MorningStar' },
  { id: 'coin_SHND', symbol: 'SHND', label: 'StrongHands' },
  { id: 'coin_PCN', symbol: 'PCN', label: 'PeepCoin' },
  { id: 'coin_FUTC', symbol: 'FUTC', label: 'FutCoin' },
  { id: 'coin_MARX', symbol: 'MARX', label: 'MarxCoin' },
  { id: 'coin_BRAT', symbol: 'BRAT', label: 'BRAT' },
  { id: 'coin_BITCF', symbol: 'BITCF', label: 'First Bitcoin...' },
  { id: 'coin_EDRC', symbol: 'EDRC', label: 'EDRCoin' },
  { id: 'coin_XQN', symbol: 'XQN', label: 'Quotient' },
  { id: 'coin_LEPEN', symbol: 'LEPEN', label: 'LePen' },
  { id: 'coin_MAGN', symbol: 'MAGN', label: 'Magnetcoin' },
  { id: 'coin_PAC', symbol: 'PAC', label: 'Paccoin' },
  { id: 'coin_NBE', symbol: 'NBE', label: 'BitCentavo' },
  { id: 'coin_ASN', symbol: 'ASN', label: 'Aseancoin' },
  { id: 'coin_TOPAZ', symbol: 'TOPAZ', label: 'Topaz Coin' },
  { id: 'coin_EMV', symbol: 'EMV', label: 'Ethereum Movi...' },
  { id: 'coin_AMIS', symbol: 'AMIS', label: 'AMIS' },
  { id: 'coin_MINEX', symbol: 'MINEX', label: 'Minex' },
  { id: 'coin_SKR', symbol: 'SKR', label: 'Sakuracoin' },
  { id: 'coin_HDLB', symbol: 'HDLB', label: 'HODL Bucks' },
  { id: 'coin_9COIN', symbol: '9COIN', label: '9COIN' },
  { id: 'coin_XSTC', symbol: 'XSTC', label: 'Safe Trade Coin' },
  { id: 'coin_BXC', symbol: 'BXC', label: 'Bitcedi' },
  { id: 'coin_RBBT', symbol: 'RBBT', label: 'RabbitCoin' },
  { id: 'coin_SKULL', symbol: 'SKULL', label: 'Pirate Blocks' },
  { id: 'coin_APC', symbol: 'APC', label: 'AlpaCoin' },
  { id: 'coin_DASHS', symbol: 'DASHS', label: 'Dashs' },
  { id: 'coin_PRES', symbol: 'PRES', label: 'President Trump' },
  { id: 'coin_B@', symbol: 'B@', label: 'Bankcoin' },
  { id: 'coin_ACN', symbol: 'ACN', label: 'Avoncoin' },
  { id: 'coin_TCOIN', symbol: 'TCOIN', label: 'T-coin' },
  { id: 'coin_SFE', symbol: 'SFE', label: 'SafeCoin' },
  { id: 'coin_AV', symbol: 'AV', label: 'AvatarCoin' },
  { id: 'coin_HYPER', symbol: 'HYPER', label: 'Hyper' },
  { id: 'coin_XAU', symbol: 'XAU', label: 'Xaucoin' },
  { id: 'coin_AIB', symbol: 'AIB', label: 'Advanced Inte...' },
  { id: 'coin_VOYA', symbol: 'VOYA', label: 'Voyacoin' },
  { id: 'coin_TODAY', symbol: 'TODAY', label: 'TodayCoin' },
  { id: 'coin_BTG', symbol: 'BTG', label: 'Bitgem' },
  { id: 'coin_BUB', symbol: 'BUB', label: 'Bubble' },
  { id: 'coin_PRN', symbol: 'PRN', label: 'Protean' },
  { id: 'coin_FRWC', symbol: 'FRWC', label: 'FrankyWillCoin' },
  { id: 'coin_BEST', symbol: 'BEST', label: 'BestChain' },
  { id: 'coin_EGG', symbol: 'EGG', label: 'EggCoin' },
  { id: 'coin_ANI', symbol: 'ANI', label: 'Animecoin' },
  { id: 'coin_QORA', symbol: 'QORA', label: 'Qora' },
  { id: 'coin_XDE2', symbol: 'XDE2', label: 'XDE II' },
  { id: 'coin_BITOK', symbol: 'BITOK', label: 'Bitok' },
  { id: 'coin_PAYP', symbol: 'PAYP', label: 'PayPeer' },
  { id: 'coin_ASC', symbol: 'ASC', label: 'AsicCoin' },
  { id: 'coin_DISK', symbol: 'DISK', label: 'DarkLisk' },
  { id: 'coin_DON', symbol: 'DON', label: 'Donationcoin' },
  { id: 'coin_WSX', symbol: 'WSX', label: 'WeAreSatoshi' },
  { id: 'coin_GAIN', symbol: 'GAIN', label: 'UGAIN' },
  { id: 'coin_OCOW', symbol: 'OCOW', label: 'OCOW' },
  { id: 'coin_SKC', symbol: 'SKC', label: 'Skeincoin' },
  { id: 'coin_AXIOM', symbol: 'AXIOM', label: 'Axiom' },
  { id: 'coin_TERA', symbol: 'TERA', label: 'TeraCoin' },
  { id: 'coin_PRM', symbol: 'PRM', label: 'PrismChain' },
  { id: 'coin_WINK', symbol: 'WINK', label: 'Wink' },
  { id: 'coin_UTA', symbol: 'UTA', label: 'UtaCoin' },
  { id: 'coin_TELL', symbol: 'TELL', label: 'Tellurion' },
  { id: 'coin_FFC', symbol: 'FFC', label: 'FireFlyCoin' },
  { id: 'coin_UNC', symbol: 'UNC', label: 'UNCoin' },
  { id: 'coin_TRICK', symbol: 'TRICK', label: 'TrickyCoin' },
  { id: 'coin_TOP', symbol: 'TOP', label: 'TopCoin' },
  { id: 'coin_RHFC', symbol: 'RHFC', label: 'RHFCoin' },
  { id: 'coin_SHA', symbol: 'SHA', label: 'SHACoin' },
  { id: 'coin_LKC', symbol: 'LKC', label: 'LinkedCoin' },
  { id: 'coin_ABC', symbol: 'ABC', label: 'Alphabit' },
  { id: 'coin_ZSE', symbol: 'ZSE', label: 'ZSEcoin' },
  { id: 'coin_YES', symbol: 'YES', label: 'Yescoin' },
  { id: 'coin_QBC', symbol: 'QBC', label: 'Quebecoin' },
  { id: 'coin_FC', symbol: 'FC', label: 'Facecoin' },
  { id: 'coin_XVE', symbol: 'XVE', label: 'The Vegan Ini...' },
  { id: 'coin_MMXVI', symbol: 'MMXVI', label: 'MMXVI' },
  { id: 'coin_COUPE', symbol: 'COUPE', label: 'Coupecoin' },
  { id: 'coin_BGR', symbol: 'BGR', label: 'Bongger' },
  { id: 'coin_ACES', symbol: 'ACES', label: 'Aces' },
  { id: 'coin_IRL', symbol: 'IRL', label: 'IrishCoin' },
  { id: 'coin_FONZ', symbol: 'FONZ', label: 'Fonziecoin' },
  { id: 'coin_NTCC', symbol: 'NTCC', label: 'Neptune Classic' },
  { id: 'coin_TCR', symbol: 'TCR', label: 'TheCreed' },
  { id: 'coin_RICHX', symbol: 'RICHX', label: 'RichCoin' },
  { id: 'coin_ELC', symbol: 'ELC', label: 'Elacoin' },
  { id: 'coin_FAZZ', symbol: 'FAZZ', label: 'Fazzcoin' },
  { id: 'coin_MONETA', symbol: 'MONETA', label: 'Moneta' },
  { id: 'coin_GMX', symbol: 'GMX', label: 'GoldMaxCoin' },
  { id: 'coin_GBRC', symbol: 'GBRC', label: 'Global Busine...' },
  { id: 'coin_MONEY', symbol: 'MONEY', label: 'MoneyCoin' },
  { id: 'coin_VGC', symbol: 'VGC', label: 'VegasCoin' },
  { id: 'coin_TURBO', symbol: 'TURBO', label: 'TurboCoin' },
  { id: 'coin_SAK', symbol: 'SAK', label: 'Sharkcoin' },
  { id: 'coin_CLINT', symbol: 'CLINT', label: 'Clinton' },
  { id: 'coin_GAY', symbol: 'GAY', label: 'GAY Money' },
  { id: 'coin_BIT', symbol: 'BIT', label: 'First Bitcoin' },
  { id: 'coin_XRY', symbol: 'XRY', label: 'Royalties' },
  { id: 'coin_LTH', symbol: 'LTH', label: 'LAthaan' },
  { id: 'coin_HCC', symbol: 'HCC', label: 'Happy Creator...' },
  { id: 'coin_WEC', symbol: 'WEC', label: 'Wowecoin' },
  { id: 'coin_POKE', symbol: 'POKE', label: 'PokeCoin' },
  { id: 'coin_PDG', symbol: 'PDG', label: 'PinkDog' },
  { id: 'coin_WOW', symbol: 'WOW', label: 'Wowcoin' },
  { id: 'coin_BIRDS', symbol: 'BIRDS', label: 'Birds' },
  { id: 'coin_DBG', symbol: 'DBG', label: 'Digital Bulli...' },
  { id: 'coin_SNAKE', symbol: 'SNAKE', label: 'SnakeEyes' },
  { id: 'coin_TLE', symbol: 'TLE', label: 'Tattoocoin (L...' },
  { id: 'coin_MAVRO', symbol: 'MAVRO', label: 'Mavro' },
  { id: 'coin_PSY', symbol: 'PSY', label: 'Psilocybin' },
  { id: 'coin_X2', symbol: 'X2', label: 'X2' },
  { id: 'coin_RCN', symbol: 'RCN', label: 'Rcoin' },
  { id: 'coin_SOUL', symbol: 'SOUL', label: 'SoulCoin' },
  { id: 'coin_OPES', symbol: 'OPES', label: 'Opescoin' },
  { id: 'coin_OMC', symbol: 'OMC', label: 'Omicron' },
  { id: 'coin_DUB', symbol: 'DUB', label: 'Dubstep' },
  { id: 'coin_TEAM', symbol: 'TEAM', label: 'TeamUp' },
  { id: 'coin_CME', symbol: 'CME', label: 'Cashme' },
  { id: 'coin_TESLA', symbol: 'TESLA', label: 'TeslaCoilCoin' },
  { id: 'coin_STCN', symbol: 'STCN', label: 'Stakecoin' },
  { id: 'coin_CC', symbol: 'CC', label: 'CyberCoin' },
  { id: 'coin_MIU', symbol: 'MIU', label: 'MIYUCoin' },
  { id: 'coin_SHELL', symbol: 'SHELL', label: 'ShellCoin' },
  { id: 'coin_PEC', symbol: 'PEC', label: 'Peacecoin' },
  { id: 'coin_SYNC', symbol: 'SYNC', label: 'Sync' },
  { id: 'coin_CYC', symbol: 'CYC', label: 'Cycling Coin' },
  { id: 'coin_GOLF', symbol: 'GOLF', label: 'Golfcoin' },
  { id: 'coin_VTY', symbol: 'VTY', label: 'Victoriouscoin' },
  { id: 'coin_DCRE', symbol: 'DCRE', label: 'DeltaCredits' },
  { id: 'coin_QBT', symbol: 'QBT', label: 'Cubits' },
  { id: 'coin_XOT', symbol: 'XOT', label: 'Internet of T...' },
  { id: 'coin_GML', symbol: 'GML', label: 'GameLeagueCoin' },
  { id: 'coin_CHEAP', symbol: 'CHEAP', label: 'Cheapcoin' },
  { id: 'coin_KARMA', symbol: 'KARMA', label: 'Karmacoin' },
  { id: 'coin_IVZ', symbol: 'IVZ', label: 'InvisibleCoin' },
  { id: 'coin_SPORT', symbol: 'SPORT', label: 'SportsCoin' },
  { id: 'coin_STRB', symbol: 'STRB', label: 'SuperTurboStake' },
  { id: 'coin_NBIT', symbol: 'NBIT', label: 'netBit' },
  { id: 'coin_GARY', symbol: 'GARY', label: 'President Joh...' },
  { id: 'coin_BAC', symbol: 'BAC', label: 'BitAlphaCoin' },
  { id: 'coin_CBD', symbol: 'CBD', label: 'CBD Crystals' },
  { id: 'coin_EXL', symbol: 'EXL', label: 'Excelcoin' },
  { id: 'coin_PI', symbol: 'PI', label: 'PiCoin' },
  { id: 'coin_ROYAL', symbol: 'ROYAL', label: 'RoyalCoin' },
  { id: 'coin_KASHH', symbol: 'KASHH', label: 'KashhCoin' },
  { id: 'coin_ANTX', symbol: 'ANTX', label: 'Antimatter' },
  { id: 'coin_LAZ', symbol: 'LAZ', label: 'Lazaruscoin' },
  { id: 'coin_FLAP', symbol: 'FLAP', label: 'FlappyCoin' },
  { id: 'coin_AXF', symbol: 'AXF', label: 'AxFunds' },
  { id: 'coin_MRC', symbol: 'MRC', label: 'microCoin' },
  { id: 'coin_BGC', symbol: 'BGC', label: 'BagCoin' },
  { id: 'coin_FEDS', symbol: 'FEDS', label: 'FedoraShare' },
  { id: 'coin_FBC', symbol: 'FBC', label: 'FiboCoins' },
  { id: 'coin_DTF', symbol: 'DTF', label: 'Digitalfund' },
];

// export const sampleData: Array<SearchingItemType> =
//   currencyList.concat(cryptoCurrencies).slice(1,600);

//export const sampleData: Array<SearchingItemType> = cryptoCurrencies;

export const sampleData: Array<{ id: string; name: string; symbol: string }> =
  cryptoCurrencies;
