import { v4 as uuid } from 'uuid';

export const cryptoCurrencyData = [
  {
    id: uuid(),
    name: 'Bitcoin',
    shorthand:'BTC',
    imgUrl: '/crypto-currencies/Bitcoin.png',
    price: '$41,936.88',
    profitRateIn24h: '3.97',
    isNegativeRateIn24h: true,
    profitRateIn7d: '7.99',
    isNegativeRateIn7d: true,
    marketCap: '$794,689,453,068',
  },
  {
    id: uuid(),
    name: 'Ethererum',
    shorthand:'ETH',
    imgUrl: '/crypto-currencies/Ethereum.png',
    price: '$2,970.80',
    profitRateIn24h: '3.62',
    isNegativeRateIn24h: true,
    profitRateIn7d: '8.18',
    isNegativeRateIn7d: true,
    marketCap: '$355,237,907,218',
  },
  {
    id: uuid(),
    name: 'Tether',
    shorthand:'USDT',
    imgUrl: '/crypto-currencies/Tether.png',
    price: '$1.00',
    profitRateIn24h: '0.01',
    isNegativeRateIn24h: false,
    profitRateIn7d: '0.01',
    isNegativeRateIn7d: true,
    marketCap: '$78,718,450,118',
  },
  {
    id: uuid(),
    name: 'BNB',
    shorthand:'BNB',
    imgUrl: '/crypto-currencies/BNB.png',
    price: '$413.95',
    profitRateIn24h: '2.82',
    isNegativeRateIn24h: true,
    profitRateIn7d: '3.72',
    isNegativeRateIn7d: true,
    marketCap: '$68,268,494,962',
  },
  {
    id: uuid(),
    name: 'XRP',
    shorthand:'XRP',
    imgUrl: '/crypto-currencies/XRP.png',
    price: '$0.8034',
    profitRateIn24h: '1.72',
    isNegativeRateIn24h: true,
    profitRateIn7d: '7.84',
    isNegativeRateIn7d: true,
    marketCap: '$38,461,188,376',
  },
  {
    id: uuid(),
    name: 'Avalanche',
    shorthand:'AVAX',
    imgUrl: '/crypto-currencies/Avalanche.png',
    price: '$89.81',
    profitRateIn24h: '3.12',
    isNegativeRateIn24h: true,
    profitRateIn7d: '5.29',
    isNegativeRateIn7d: true,
    marketCap: '$22,130,509,307',
  },
  {
    id: uuid(),
    name: 'Terra',
    shorthand:'LUNA',
    imgUrl: '/crypto-currencies/Terra.png',
    price: '$54.14',
    profitRateIn24h: '3.05',
    isNegativeRateIn24h: true,
    profitRateIn7d: '4.47',
    isNegativeRateIn7d: true,
    marketCap: '$21,314,371,610',
  },
  {
    id: uuid(),
    name: 'Dogecoin',
    shorthand:'DOGE',
    imgUrl: '/crypto-currencies/Dogecoin.png',
    price: '$0.1442',
    profitRateIn24h: '2.32',
    isNegativeRateIn24h: true,
    profitRateIn7d: '8.45',
    isNegativeRateIn7d: true,
    marketCap: '$19,147,109,955',
  },
  {
    id: uuid(),
    name: 'Litecoin',
    shorthand:'LTC',
    imgUrl: '/crypto-currencies/Litecoin.png',
    price: '$122.63',
    profitRateIn24h: '2.76',
    isNegativeRateIn24h: true,
    profitRateIn7d: '12.90',
    isNegativeRateIn7d: true,
    marketCap: '$8,548,303,127',
  },
  {
    id: uuid(),
    name: 'Polkadot',
    shorthand:'DOT',
    imgUrl: '/crypto-currencies/Polkadot.png',
    price: '$18.58',
    profitRateIn24h: '3.39',
    isNegativeRateIn24h: true,
    profitRateIn7d: '15.20',
    isNegativeRateIn7d: true,
    marketCap: '$18,352,106,211',
  }
];
