export const dummyNews:any=[
    {
        "cols":2,
        "rows":2,
        "category": "top news",
        "datetime": 1655454960,
        "headline": "Dow Jones Newswires: Glencore raises coal price, cost guidance amid ‘unprecedented’ environment",
        "id": 7106899,
        "image": "https://images.mktw.net/im-551107/social",
        "related": "",
        "source": "Market Watch",
        "summary": "\"Unprecedented dislocation\" in energy markets has resulted in record pricing differentials between coal benchmarks and quality categories, says Glencore.",
        "url": "https://www.marketwatch.com/story/glencore-raises-coal-price-cost-guidance-amid-unprecedented-environment-update-271655450927"
    },
    {
        "cols":2,
        "category": "top news",
        "datetime": 1655454660,
        "headline": "Dow Jones Newswires: BOJ’s Kuroda says rapid yen weakening negative for economy",
        "id": 7106900,
        "image": "https://images.mktw.net/im-566233/social",
        "related": "",
        "source": "MarketWatch",
        "summary": "Earlier in the day, the bank's policy board decided to maintain ultralow interest rates, moving against a global trend of monetary tightening amid inflation.",
        "url": "https://www.marketwatch.com/story/boj-s-kuroda-says-rapid-yen-weakening-negative-for-economy-271655452473"
    },
    {
        "cols":2,
        "category": "top news",
        "datetime": 1655452854,
        "headline": "Protests Rage Over India's New Military Recruitment Policy",
        "id": 7106906,
        "image": "https://data.bloomberglp.com/company/sites/2/2019/01/logobbg-wht.png",
        "related": "",
        "source": "Bloomberg",
        "summary": "New Delhi (AP) -- Hundreds of youths in India burned train coaches, vandalized railroad property and blocked rail tracks and highways with boulders as an angry backlash continued for a second day Friday against a new short-term government recruitment policy f…",
        "url": "https://www.bloomberg.com/news/articles/2022-06-17/protests-rage-over-india-s-new-military-recruitment-policy"
    },
    {
        "category": "top news",
        "datetime": 1655451561,
        "headline": "Analyze how companies deploy capital in different industries",
        "id": 7106893,
        "image": "https://data.bloomberglp.com/company/sites/2/2019/01/logobbg-wht.png",
        "related": "",
        "source": "Bloomberg",
        "summary": "Here are how different industries such as energy, banking and technology are currently utilizing their capital.",
        "url": "https://www.bloomberg.com/professional/blog/analyze-how-companies-deploy-capital-in-different-industries/"
    },
    {
        "category": "top news",
        "datetime": 1655450315,
        "headline": "Klarna’s Value Falls to $15 Billion as Seeks Funds, Journal Says",
        "id": 7106891,
        "image": "https://data.bloomberglp.com/company/sites/2/2019/01/logobbg-wht.png",
        "related": "",
        "source": "Bloomberg",
        "summary": "Swedish payments firm Klarna Bank AB is looking to raise less capital than earlier planned and at a much lower valuation of $15 billion, the Wall Street Journal reported citing people familiar with the matter.",
        "url": "https://www.bloomberg.com/news/articles/2022-06-17/klarna-s-value-falls-to-15-billion-as-seeks-funds-journal-says"
    },
    {
        "category": "top news",
        "datetime": 1655450260,
        "headline": "Ukraine Latest: Australia Joins Regional Leaders in NATO Visit",
        "id": 7106894,
        "image": "https://data.bloomberglp.com/company/sites/2/2019/01/logobbg-wht.png",
        "related": "",
        "source": "Bloomberg",
        "summary": "Australia’s Prime Minister Anthony Albanese will head to Europe for a NATO meeting in late June, in what the new premier has described as a show of support for Ukraine in the face of “thuggish, illegal behavior” by Russia.",
        "url": "https://www.bloomberg.com/news/articles/2022-06-17/ukraine-latest-australia-joins-regional-leaders-in-nato-visit"
    },
    {
        "category": "top news",
        "datetime": 1655449800,
        "headline": "Xi Claims Victory in Anti-Graft Campaign Targeting China’s Banks",
        "id": 7106907,
        "image": "https://data.bloomberglp.com/company/sites/2/2019/01/logobbg-wht.png",
        "related": "",
        "source": "Bloomberg",
        "summary": "China’s Politburo declared its anti-corruption dragnet of financial institutions a success, in a potential sign of relief for the $59 trillion sector.",
        "url": "https://www.bloomberg.com/news/articles/2022-06-17/xi-claims-victory-in-anti-graft-campaign-targeting-china-s-banks"
    },
    {
        "category": "top news",
        "datetime": 1655449273,
        "headline": "A Journey to Kyiv by Top European Leaders: The Political Week in Photos",
        "id": 7106908,
        "image": "https://data.bloomberglp.com/company/sites/2/2019/01/logobbg-wht.png",
        "related": "",
        "source": "Bloomberg",
        "summary": "German Chancellor Olaf Scholz, French President Emmanuel Macron and Italian Prime Minister Mario Draghi witnessed the damage caused by Russia’s war in Ukraine and met with President Volodymyr Zelenskiy in a show of  support for Kyiv.",
        "url": "https://www.bloomberg.com/news/photo-essays/2022-06-17/a-journey-to-kyiv-by-top-european-leaders-the-political-week-in-photos"
    },
    {
        "category": "top news",
        "datetime": 1655448084,
        "headline": "Tesco's UK Sales Miss as Cost of Living Bites: The London Rush",
        "id": 7106887,
        "image": "https://data.bloomberglp.com/company/sites/2/2019/01/logobbg-wht.png",
        "related": "",
        "source": "Bloomberg",
        "summary": "Here’s the key business news from London-listed companies this morning.",
        "url": "https://www.bloomberg.com/news/articles/2022-06-17/tesco-s-uk-sales-miss-as-cost-of-living-bites-the-london-rush"
    },
    {
        "category": "top news",
        "datetime": 1655447260,
        "headline": "Hong Kong’s Lam Urges Caution But Refrains From New Covid Curbs",
        "id": 7106881,
        "image": "https://data.bloomberglp.com/company/sites/2/2019/01/logobbg-wht.png",
        "related": "",
        "source": "Bloomberg",
        "summary": "Hong Kong’s outgoing leader Carrie Lam urged residents to avoid banquets and other large gatherings amid a resurgence in the Asian financial hub’s Covid-19 outbreak, but held off from imposing new social distancing restrictions as the number of serious infect…",
        "url": "https://www.bloomberg.com/news/articles/2022-06-17/hong-kong-to-boost-covid-restrictions-without-new-closures-scmp"
    },
    {
        "category": "top news",
        "datetime": 1655446996,
        "headline": "London's Gatwick Airport Limits Capacity as Staffing Woes Bite",
        "id": 7106888,
        "image": "https://data.bloomberglp.com/company/sites/2/2019/01/logobbg-wht.png",
        "related": "",
        "source": "Bloomberg",
        "summary": "London’s Gatwick airport said it will limit airline capacity over the peak summer travel period amid staffing shortages that caused chaos during the recent Jubilee holidays.",
        "url": "https://www.bloomberg.com/news/articles/2022-06-17/london-s-gatwick-airport-limits-capacity-as-staffing-woes-bite"
    },
    {
        "category": "top news",
        "datetime": 1655446701,
        "headline": "Tesco UK Sales Drop as Cost of Living Weighs on Shoppers",
        "id": 7106879,
        "image": "https://data.bloomberglp.com/company/sites/2/2019/01/logobbg-wht.png",
        "related": "",
        "source": "Bloomberg",
        "summary": "Tesco Plc said sales in the UK are falling in an “incredibly challenging” market as consumers are squeezed by the higher cost of living.",
        "url": "https://www.bloomberg.com/news/articles/2022-06-17/tesco-uk-sales-drop-as-cost-of-living-weighs-on-shoppers"
    },
    {
        "category": "top news",
        "datetime": 1655446500,
        "headline": "Dow Jones Newswires: Banco Santander: Hector Grisi to succeed Jose Antonio Alvarez as CEO",
        "id": 7106871,
        "image": "https://images.mktw.net/im-250235/social",
        "related": "",
        "source": "MarketWatch",
        "summary": "Mr. Alvarez will continue on the board of directors as a nonexecutive vice chair, Santander said.",
        "url": "https://www.marketwatch.com/story/banco-santander-hector-grisi-to-succeed-jose-antonio-alvarez-as-ceo-271655443953"
    },
    {
        "category": "top news",
        "datetime": 1655446381,
        "headline": "Volkswagen to Pay $80 Million Over Porsche Fuel Tests After Cheating Scandal",
        "id": 7106880,
        "image": "https://data.bloomberglp.com/company/sites/2/2019/01/logobbg-wht.png",
        "related": "",
        "source": "Bloomberg",
        "summary": "Volkswagen AG agreed to pay at least $80 million to settle Porsche buyers’ complaints that emissions and fuel economy test results were improperly skewed.",
        "url": "https://www.bloomberg.com/news/articles/2022-06-16/volkswagen-to-pay-80-million-over-skewed-porsche-fuel-tests"
    },
    {
        "category": "top news",
        "datetime": 1655446009,
        "headline": "China’s Newest Aircraft Carrier Fujian Shows Xi Jinping Catching Up With US",
        "id": 7106874,
        "image": "https://data.bloomberglp.com/company/sites/2/2019/01/logobbg-wht.png",
        "related": "",
        "source": "Bloomberg",
        "summary": "China launched its third and most modern aircraft carrier, a watershed moment for President Xi Jinping’s efforts to modernize the armed forces and narrow his country’s military gap with the US.",
        "url": "https://www.bloomberg.com/news/articles/2022-06-17/china-s-newest-aircraft-carrier-shows-xi-jinping-catching-up-with-us"
    },
    {
        "category": "top news",
        "datetime": 1655445824,
        "headline": "Sri Lanka’s Economy Grinds to a Halt as Fuel Supplies Run Dry",
        "id": 7106875,
        "image": "https://data.bloomberglp.com/company/sites/2/2019/01/logobbg-wht.png",
        "related": "",
        "source": "Bloomberg",
        "summary": "Sri Lanka’s economic activity is coming to a near standstill as the island nation, facing its worst financial crisis, runs out of fuel for transport and there’s little signs of fresh supplies coming in.",
        "url": "https://www.bloomberg.com/news/articles/2022-06-17/sri-lanka-s-economy-grinds-to-a-halt-as-fuel-supplies-run-dry"
    },
    {
        "category": "top news",
        "datetime": 1655443396,
        "headline": "Warriors Beat Celtics 103-90 to Win 4th NBA Title in 8 Years",
        "id": 7106869,
        "image": "https://data.bloomberglp.com/company/sites/2/2019/01/logobbg-wht.png",
        "related": "",
        "source": "Bloomberg",
        "summary": "Boston (AP) -- The Golden State Warriors are NBA champions once again, topping the Boston Celtics 103-90 on Thursday night for their fourth title in the last eight seasons.",
        "url": "https://www.bloomberg.com/news/articles/2022-06-17/warriors-beat-celtics-103-90-to-win-4th-nba-title-in-8-years"
    },
    {
        "category": "top news",
        "datetime": 1655442530,
        "headline": "EU Aims for Calm Amid Economic Turbulence",
        "id": 7106863,
        "image": "https://data.bloomberglp.com/company/sites/2/2019/01/logobbg-wht.png",
        "related": "",
        "source": "Bloomberg",
        "summary": "Welcome to the Brussels Edition, Bloomberg’s daily briefing on what matters most in the heart of the European Union.",
        "url": "https://www.bloomberg.com/news/newsletters/2022-06-17/eu-aims-for-calm-amid-economic-turbulence"
    }]